import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const worker=(await import(pathToFileURL(process.cwd()+'/dist/server/index.js'))).default;
const env={STORE_PASSWORD:'verification-password',SESSION_SECRET:'test-secret-for-local-validation-only'};
const origin='https://test.local';
const req=(route,opts={})=>new Request(origin+route,opts);
const run=(route,opts)=>worker.fetch(req(route,opts),env);
assert.equal((await run('/')).status,200);
assert.equal((await run('/app.js')).status,401);
assert.equal((await run('/config.js')).status,401);
assert.equal((await run('/assets/art.png')).status,401);
assert.equal((await run('/assets/mark.jpg')).status,200);
assert.equal((await run('/acceso',{method:'POST',headers:{Origin:origin},body:'password=wrong'})).status,401);
assert.equal((await run('/acceso',{method:'POST',headers:{Origin:'https://other.local'},body:'password=verification-password'})).status,403);
const login=await run('/acceso',{method:'POST',headers:{Origin:origin},body:'password=verification-password'});
assert.equal(login.status,303);assert.equal(login.headers.get('Location'),'/catalogo');
const fullCookie=login.headers.get('Set-Cookie');assert.match(fullCookie,/HttpOnly; Secure; SameSite=Lax/);
const cookie=fullCookie.split(';')[0];
const catalog=await run('/catalogo',{headers:{Cookie:cookie}});assert.equal(catalog.status,200);assert.match(await catalog.text(),/mobile.css/);
const config=await run('/config.js',{headers:{Cookie:cookie}});assert.match(await config.text(),/@bossin_around/);
assert.equal((await run('/app.js',{headers:{Cookie:cookie+'bad'}})).status,401);
const logout=await run('/salir',{method:'POST',headers:{Origin:origin,Cookie:cookie}});assert.match(logout.headers.get('Set-Cookie'),/Max-Age=0/);
assert.equal((await worker.fetch(req('/'),{})).status,503);
console.log('PASS: login, wrong password, cookie signature, protected routes, CSRF, logout, Telegram and fail-closed configuration.');

const adminEnv={...env,ADMIN_USERNAME:'admin',ADMIN_PASSWORD:'test-admin-password'};
const adminRun=(route,opts={})=>worker.fetch(req(route,opts),adminEnv);
assert.equal((await adminRun('/admin')).status,200);
assert.equal((await adminRun('/admin/api/profiles',{headers:{Cookie:cookie}})).status,401);
assert.equal((await adminRun('/admin/admin.js',{headers:{Cookie:cookie}})).status,401);
assert.equal((await adminRun('/admin/acceso',{method:'POST',headers:{Origin:origin},body:'username=admin&password=verification-password'})).status,401);
const adminLogin=await adminRun('/admin/acceso',{method:'POST',headers:{Origin:origin},body:'username=admin&password=test-admin-password'});
assert.equal(adminLogin.status,303);const adminCookie=adminLogin.headers.get('Set-Cookie').split(';')[0];
assert.equal((await adminRun('/admin',{headers:{Cookie:adminCookie}})).status,200);
assert.equal((await adminRun('/admin/Perfiles.gs',{headers:{Cookie:adminCookie}})).status,200);
assert.equal((await adminRun('/admin/api/profile',{method:'POST',headers:{Origin:'https://bad.local',Cookie:adminCookie},body:'{}'})).status,403);
assert.equal((await adminRun('/admin/api/profiles',{headers:{Cookie:adminCookie.replace('dollars_admin','dollars_session')}})).status,401);
const notConnected=await adminRun('/admin/api/profiles',{headers:{Cookie:adminCookie}});assert.equal((await notConnected.json()).connected,false);
const withSource={...adminEnv,CATALOG_ENDPOINT:'https://script.google.com/macros/s/test/exec',CATALOG_TOKEN:'test-token'};
const originalFetch=globalThis.fetch;let sent;
globalThis.fetch=async(url,options)=>{sent=JSON.parse(options.body);return Response.json(sent.action==='profile'?{profile:{id:'1',name:'Test',country:'Argentina',available:true,details:{age:'22',notes:'Valid',email:'not allowed'}}}:{profiles:[{id:'1',name:'Test',available:false,details:{email:'not allowed'},email:'not allowed',approved:true,eligible:true,revision:'v1'}]});};
try{const listing=await worker.fetch(req('/api/profiles',{headers:{Cookie:cookie}}),withSource);assert(!JSON.stringify(await listing.json()).includes('not allowed'));const detailed=await worker.fetch(req('/api/profile?id=1',{headers:{Cookie:cookie}}),withSource);const content=await detailed.json();assert.equal(content.profile.details.age,'22');assert(!JSON.stringify(content).includes('not allowed'));assert.equal(sent.action,'profile');assert.equal(sent.token,'test-token');}finally{globalThis.fetch=originalFetch;}
console.log('PASS: separate admin credentials/session, protected admin code/API, CSRF, connection state, upstream field allowlist.');
