/** REEMPLAZAR TODO Código.gs CON ESTE ARCHIVO. No envolver en myFunction().
 * Ejecutar prepararPerfiles; luego implementar como aplicación web.
 */
const SHEET_ID='1TVEuvhJtnvHDB12x0hrebl6QGKrdfMmpAJaSxFkMycQ';
const FIELD_COLUMNS={onlyfansStatus:'OnlyFans status',monthlyRevenue:'Monthly Revenue',currentSubscribers:'Current Subscribers',contentLibrary:'Ya tiene contenidos creados',notes:'Notes / Highlights',age:'Edad',country:'País de origen',english:'Nivel de ingles',creatorType:'Creator Type',smartphone:'Smartphone',countriesBlocked:'Países bloqueados',accountAccess:'Account access',revenueSplit:'Revenue Split (%)',dailyWeeklyAvailability:'Availability Day/Week',startAvailability:'Start Availability',agency:'Actualmente con agencia?',socialMedia:'Social Media Set Up',contentType:'Tipo de contenido aceptado'};
function tablaPerfiles(){const ss=SpreadsheetApp.openById(SHEET_ID);for(const sheet of ss.getSheets()){if(!sheet.getLastColumn())continue;const rows=sheet.getDataRange().getValues(),headers=rows[0].map(x=>String(x).trim());if(['Nombre','Edad','País de origen','Nivel de ingles','Fotos del perfil'].every(x=>headers.includes(x)))return {sheet,rows,headers};}throw new Error('No se encontró la pestaña de respuestas con los encabezados esperados.');}
function prepararPerfiles(){
 const lock=LockService.getScriptLock();lock.waitLock(30000);
 try{const {sheet}=tablaPerfiles();let headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0].map(x=>String(x).trim());
 for(const title of ['Publicar','Perfil ID','Disponible','Nombre publicado','Fotos publicadas','Listing Price USD',...Object.values(FIELD_COLUMNS)])if(!headers.includes(title)){sheet.getRange(1,sheet.getLastColumn()+1).setValue(title);headers.push(title);}
 const count=Math.max(sheet.getLastRow()-1,0);if(count){for(const title of ['Publicar','Disponible'])sheet.getRange(2,headers.indexOf(title)+1,count).setDataValidation(SpreadsheetApp.newDataValidation().requireCheckbox().build());const range=sheet.getRange(2,headers.indexOf('Perfil ID')+1,count),ids=range.getValues();for(let i=0;i<ids.length;i++)if(!ids[i][0])ids[i][0]=Utilities.getUuid();range.setValues(ids);}
 const props=PropertiesService.getScriptProperties();if(!props.getProperty('CATALOG_TOKEN'))props.setProperty('CATALOG_TOKEN',Utilities.getUuid()+Utilities.getUuid());
 if(!ScriptApp.getProjectTriggers().some(t=>t.getHandlerFunction()==='nuevoPerfil'))ScriptApp.newTrigger('nuevoPerfil').forSpreadsheet(SHEET_ID).onFormSubmit().create();
 console.log('Preparado. Las respuestas se administran desde el panel.');console.log('CATALOG_TOKEN está en Configuración del proyecto > Propiedades del script.');
 }finally{lock.releaseLock();}
}
function nuevoPerfil(e){if(!e?.range)return;const lock=LockService.getScriptLock();lock.waitLock(30000);try{const {sheet,headers}=tablaPerfiles();if(e.range.getSheet().getSheetId()!==sheet.getSheetId())return;const row=e.range.getRow(),id=headers.indexOf('Perfil ID')+1;if(!id)throw new Error('Ejecutá prepararPerfiles primero.');if(!sheet.getRange(row,id).getValue())sheet.getRange(row,id).setValue(Utilities.getUuid());for(const title of ['Publicar','Disponible']){const col=headers.indexOf(title)+1;if(col)sheet.getRange(row,col).insertCheckboxes().setValue(false);}}finally{lock.releaseLock();}}
function versionPerfil(row){return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,JSON.stringify(row)));}
function fotosGuardadas(editorial,original){if(String(editorial).trim()){try{const ids=JSON.parse(String(editorial));return Array.isArray(ids)?[...new Set(ids.filter(x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{10,}$/.test(x)))]:[];}catch{return [];}}return [...new Set([...String(original).matchAll(/(?:\/d\/|[?&]id=)([a-zA-Z0-9_-]{10,})/g)].map(m=>m[1]))];}
function registros(){const table=tablaPerfiles();const get=(row,name)=>{const i=table.headers.indexOf(name);return i<0?'':row[i];};return {...table,profiles:table.rows.slice(1).map((row,index)=>{const age=String(get(row,'Edad')).trim();const eligible=/^\d{2,3}$/.test(age)&&Number(age)>=18&&Number(age)<=120;const details=Object.fromEntries(Object.entries(FIELD_COLUMNS).map(([key,col])=>[key,String(get(row,col)??'')]));if(!details.dailyWeeklyAvailability)details.dailyWeeklyAvailability=String(get(row,'Disponibilidad diaria')||'');return {row:index+2,id:String(get(row,'Perfil ID')||''),name:String(get(row,'Nombre publicado')||get(row,'Nombre')||''),country:details.country,english:details.english,photos:fotosGuardadas(get(row,'Fotos publicadas'),get(row,'Fotos del perfil')),available:get(row,'Disponible')===true,approved:get(row,'Publicar')===true,eligible,details,revision:versionPerfil(row),listingPrice:String(get(row,'Listing Price USD')||''),originalRevenue:String(get(row,'Ingreso mensual/subs')||'')};}).filter(p=>p.id&&p.name)};}
function tarjeta(p){return {id:p.id,name:p.name,country:p.country,english:p.english,available:p.available,hasPhoto:p.photos.length>0};}
function detalle(p){return {...tarjeta(p),details:p.details,photoCount:p.photos.length};}
function actualizarPerfil(data){
 if(typeof data.id!=='string'||typeof data.revision!=='string'||(data.approved!==undefined&&typeof data.approved!=='boolean')||(data.available!==undefined&&typeof data.available!=='boolean'))return {error:'invalid_request'};
 if(data.name!==undefined&&(typeof data.name!=='string'||!data.name.trim()||data.name.length>120))return {error:'invalid_name'};
 if(data.photos!==undefined&&(!Array.isArray(data.photos)||data.photos.length>30||new Set(data.photos).size!==data.photos.length||!data.photos.every(x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{10,}$/.test(x))))return {error:'invalid_photos'};
 if(data.details&&(!Object.keys(data.details).every(k=>Object.prototype.hasOwnProperty.call(FIELD_COLUMNS,k)&&typeof data.details[k]==='string'&&data.details[k].length<=1000)))return {error:'invalid_fields'};
 const lock=LockService.getScriptLock();lock.waitLock(30000);
 try{const {sheet,profiles,headers}=registros(),p=profiles.find(x=>x.id===data.id);if(!p)return {error:'not_found'};if(p.revision!==data.revision)return {error:'conflict'};
 if(data.photos&&data.photos.some(id=>!p.photos.includes(id)))return {error:'invalid_photos'};
 const details={...p.details,...data.details};const age=String(details.age).trim();const eligible=/^\d{2,3}$/.test(age)&&Number(age)>=18&&Number(age)<=120;
 const approved=data.approved===undefined?p.approved:data.approved;if(approved&&!eligible)return {error:'adult_required'};
 let available=data.available===undefined?p.available:data.available;if(approved&&!p.approved)available=true;if(!approved)available=false;
 const updates=[];if(data.listingPrice!==undefined){const col=headers.indexOf('Listing Price USD')+1;if(!col)return {error:'setup_required'};updates.push([col,data.listingPrice]);}for(const [key,col] of [['name','Nombre publicado'],['photos','Fotos publicadas']])if(data[key]!==undefined){const column=headers.indexOf(col)+1;if(!column)return {error:'setup_required'};updates.push([column,key==='photos'?JSON.stringify(data.photos):data.name.trim()]);}for(const [k,v] of Object.entries(data.details||{})){const col=headers.indexOf(FIELD_COLUMNS[k])+1;if(!col)return {error:'setup_required'};updates.push([col,v]);}const pub=headers.indexOf('Publicar')+1,avail=headers.indexOf('Disponible')+1;if(!pub||!avail)return {error:'setup_required'};
 // Solo columnas permitidas; las fórmulas se guardan como texto literal.
 for(const [col,value] of updates)sheet.getRange(p.row,col).setValue(/^[=+@-]/.test(value)?"'"+value:value);
 sheet.getRange(p.row,pub).setValue(approved);sheet.getRange(p.row,avail).setValue(available);SpreadsheetApp.flush();return {ok:true};
 }finally{lock.releaseLock();}
}
function fotoPerfil(p,index=0){if(!Number.isInteger(index)||index<0)return {error:'not_found'};const id=p.photos[index];if(!id)return {error:'photo_requires_drive'};const file=DriveApp.getFileById(id),blob=file.getThumbnail()||file.getBlob(),bytes=blob.getBytes();if(!['image/jpeg','image/png','image/webp'].includes(blob.getContentType())||bytes.length>2000000)return {error:'unsupported_photo'};return {mime:blob.getContentType(),base64:Utilities.base64Encode(bytes)};}
function doPost(e){const json=value=>ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);try{const data=JSON.parse(e.postData.contents),secret=PropertiesService.getScriptProperties().getProperty('CATALOG_TOKEN');if(!secret||data.token!==secret)return json({error:'unauthorized'});
 if(data.action==='telegramPreview')return json(vistaTelegram(data));
 if(data.action==='telegramPublish')return json(publicarTelegram(data));
 if(data.action==='adminUpdate')return json(actualizarPerfil(data));
 const {profiles}=registros();const approved=profiles.filter(p=>p.eligible&&p.approved);
 if(data.action==='profiles')return json({profiles:approved.map(tarjeta)});
 if(data.action==='profile'){const p=approved.find(p=>p.id===data.id);return json(p?{profile:detalle(p)}:{error:'not_found'});}
 if(data.action==='adminList')return json({editingVersion:2,telegramVersion:1,profiles:profiles.map(p=>({...detalle(p),photos:p.photos,hasPhoto:p.eligible&&p.photos.length>0,eligible:p.eligible,approved:p.approved,revision:p.revision,listingPrice:p.listingPrice,originalRevenue:p.originalRevenue}))});
 if(data.action==='photo'||data.action==='adminPhoto'){const p=(data.action==='adminPhoto'?profiles.filter(p=>p.eligible):approved).find(p=>p.id===data.id);return json(p?fotoPerfil(p,data.index===undefined?0:data.index):{error:'not_found'});}
 return json({error:'invalid_action'});
 }catch(error){console.error("Connector request failed");return json({error:'source_unavailable'});}}
function doGet(){return ContentService.createTextOutput('Conector DOLL ARS activo. El acceso a los datos requiere autenticación.').setMimeType(ContentService.MimeType.TEXT);}

// This file is appended to Perfiles.gs by the build; no tokens belong in source.
const TELEGRAM_SECTIONS=[['PERFORMANCE SNAPSHOT',['onlyfansStatus','monthlyRevenue','currentSubscribers','contentLibrary','notes']],['CREATOR PROFILE',['age','country','english','creatorType','smartphone']],['COLLABORATION PREFERENCES',['countriesBlocked','accountAccess','revenueSplit','dailyWeeklyAvailability','startAvailability','agency','socialMedia','contentType']]];
const TELEGRAM_LABELS=['Onlyfans Status','Monthly Revenue','Current Subscribers','Content Library','Notes / Highlights','Age','Country','English Level','Creator Type','Smartphone','Countries Blocked','Account access','Revenue Split (%)','Availability Day/Week','Start Availability','Currently Working w/Agency','Social Media Set Up','Content Type'];
function perfilTelegram(data){const p=registros().profiles.find(p=>p.id===data.id);if(!p)return {error:'not_found'};if(!p.approved||!p.eligible)return {error:'adult_approved_required'};if(p.revision!==data.revision)return {error:'conflict'};if(!/^\d{1,9}(\.\d{1,2})?$/.test(p.listingPrice)||Number(p.listingPrice)<=0)return {error:'invalid_price'};return p;}
function vistaTelegram(data){const p=perfilTelegram(data);if(p.error)return p;const props=PropertiesService.getScriptProperties();if(!props.getProperty('TELEGRAM_BOT_TOKEN'))return {error:'telegram_setup'};let label=0;const lines=[p.name,''];for(const [title,keys] of TELEGRAM_SECTIONS){if(label)lines.push('⸻');lines.push(title);for(const k of keys){const value=p.details[k].trim();const english=value?(/^[\d\s.,%$]+$/.test(value)?value:LanguageApp.translate(value,'','en')):'Not provided';lines.push((k==='creatorType'?'🖤':'🤍')+' '+TELEGRAM_LABELS[label++]+': '+english);}}lines.push('⸻','COMMERCIAL TERMS','🩵 Listing Price: $'+p.listingPrice+' USD','🩵 Guarantee: 18-day replacement or refund policy');const text=lines.join('\n');if(text.length>4096)return {error:'telegram_text_long'};const draft=Utilities.getUuid();CacheService.getScriptCache().put('tg-draft-'+draft,JSON.stringify({id:p.id,revision:p.revision}),600);return {text,draft,channel:'@dollarsofm',photoCount:p.photos.length};}
function telegramRequest(method,payload,multipart=false){const token=PropertiesService.getScriptProperties().getProperty('TELEGRAM_BOT_TOKEN');if(!token)throw new Error('telegram_setup');const response=UrlFetchApp.fetch('https://api.telegram.org/bot'+token+'/'+method,{method:'post',...(multipart?{payload}:{contentType:'application/json',payload:JSON.stringify(payload)}),muteHttpExceptions:true});const result=JSON.parse(response.getContentText());if(!result.ok)throw new Error('telegram_rejected');return result.result;}
function publicarTelegram(data){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const p=perfilTelegram(data);if(p.error)return p;const cache=CacheService.getScriptCache(),raw=cache.get('tg-draft-'+data.draft);if(!raw)return {error:'draft_expired'};const draft=JSON.parse(raw);if(draft.id!==p.id||draft.revision!==p.revision)return {error:'conflict'};if(typeof data.text!=='string'||!data.text.trim()||data.text.length>4096)return {error:'telegram_text_long'};
 const props=PropertiesService.getScriptProperties(),recordKey='tg-published-'+p.id,previous=props.getProperty(recordKey);if(previous)return {error:'already_published'};
 const me=telegramRequest('getMe',{}),member=telegramRequest('getChatMember',{chat_id:'@dollarsofm',user_id:me.id});if(me.username!=='Dollars_manager_bot'||!(member.status==='creator'||member.status==='administrator'&&member.can_post_messages))return {error:'telegram_permissions'};
 // Reserve before sending. An uncertain network outcome must never silently retry.
 props.setProperty(recordKey,JSON.stringify({state:'sending',at:new Date().toISOString()}));cache.remove('tg-draft-'+data.draft);
 try{const message=telegramRequest('sendMessage',{chat_id:'@dollarsofm',text:data.text,link_preview_options:{is_disabled:true}});props.setProperty(recordKey,JSON.stringify({state:'text_sent',messageId:message.message_id}));
 let warning='';try{for(let start=0;start<p.photos.length;start+=10){const count=Math.min(10,p.photos.length-start),payload={chat_id:'@dollarsofm'},media=[];for(let i=0;i<count;i++){const photo=fotoPerfil(p,start+i);if(photo.error)throw new Error('photo_unavailable');payload['photo'+i]=Utilities.newBlob(Utilities.base64Decode(photo.base64),photo.mime,'photo'+i+'.'+(photo.mime==='image/png'?'png':photo.mime==='image/webp'?'webp':'jpg'));media.push({type:'photo',media:'attach://photo'+i});}if(count===1)telegramRequest('sendPhoto',{chat_id:payload.chat_id,photo:payload.photo0},true);else{payload.media=JSON.stringify(media);telegramRequest('sendMediaGroup',payload,true);}}}catch{warning='photos_incomplete';}
 props.setProperty(recordKey,JSON.stringify({state:warning?'photos_incomplete':'published',messageId:message.message_id}));return {ok:true,warning,url:'https://t.me/dollarsofm/'+message.message_id};
 }catch{return {error:'telegram_uncertain'};}
 }finally{lock.releaseLock();}}
