const config=window.STORE_CONFIG;
const $=id=>document.getElementById(id);
let profiles=[],country='Todos',detailRequest;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function imageFor(p,cls='product-image'){const wrap=el('span',cls);const img=el('img');img.alt='Foto de '+p.name;img.loading='lazy';if(p.image)img.src=p.image;else{wrap.append(el('span','image-fallback','Sin foto'));return wrap;}img.onerror=()=>wrap.replaceChildren(el('span','image-fallback','Foto no disponible'));wrap.append(img);return wrap;}
function safeImage(value){try{const url=new URL(value,location.origin);return url.origin===location.origin&&url.pathname==='/api/profile-photo'?url.href:'';}catch{return '';}}
function normalize(rows){if(!Array.isArray(rows))throw Error('Formato inválido');return rows.filter(p=>p.id&&p.name).map(p=>({id:String(p.id),name:String(p.name),country:String(p.country||'Sin especificar'),english:String(p.english||'Sin especificar'),available:p.available===true,image:safeImage(p.image||'')}));}
function filters(){const root=$('categories');root.replaceChildren();for(const c of ['Todos',...new Set(profiles.map(p=>p.country))]){const b=el('button','',c);b.type='button';b.setAttribute('aria-pressed',String(country===c));b.onclick=()=>{country=c;filters();render();};root.append(b);}}
function results(){const term=$('search').value.toLocaleLowerCase('es').trim();const english=$('sort').value;return profiles.filter(p=>(country==='Todos'||p.country===country)&&(!english||p.english===english)&&[p.name,p.country,p.english].join(' ').toLocaleLowerCase('es').includes(term)).sort((a,b)=>a.name.localeCompare(b.name,'es'));}
function nationality(p){const row=el('span','profile-country');const flag=countryFlag(p.country);if(flag){const icon=el('span','country-flag',flag);icon.setAttribute('aria-hidden','true');row.append(icon);}row.append(document.createTextNode(p.country));return row;}
function availability(p){return el('span','availability '+(p.available?'available':'unavailable'),p.available?'Disponible':'No disponible');}
function render(){const rows=results();$('count').textContent=rows.length+' '+(rows.length===1?'perfil':'perfiles');$('products').replaceChildren();$('empty').hidden=rows.length>0||!profiles.length;for(const p of rows){const b=el('button','product');b.type='button';b.setAttribute('aria-label','Ver perfil de '+p.name);b.append(imageFor(p),el('span','product-name',p.name));const meta=el('span','product-bottom');meta.append(nationality(p),availability(p));b.append(meta);b.onclick=()=>openProfile(p);$('products').append(b);}}
async function openProfile(p){detailRequest?.abort();detailRequest=new AbortController();const root=$('detail-content');const info=el('div','detail-info');const title=el('h2','',p.name);title.id='detail-title';info.append(title,el('p','','Cargando perfil…'));root.replaceChildren(imageFor(p,'detail-picture'),info);if(!$('detail').open)$('detail').showModal();try{const response=await fetch('/api/profile?id='+encodeURIComponent(p.id),{signal:detailRequest.signal,cache:'no-store'});if(!response.ok)throw Error('No disponible');const {profile}=await response.json();info.replaceChildren(title,nationality(profile),availability(profile),renderProfileSections(profile.details));const link=el('a','button',profile.available?'Consultar por Telegram':'Consultar disponibilidad');const url=new URL('https://t.me/'+config.telegram.replace(/^@/,''));url.searchParams.set('text','Hola, quisiera consultar por el perfil de '+profile.name+' ('+profile.id+').');link.href=url.href;link.target='_blank';link.rel='noopener';info.append(link,el('p','small','Continuá la consulta directamente por Telegram.'));}catch(error){if(error.name==='AbortError')return;info.replaceChildren(title,el('p','','El perfil no está disponible en este momento.'));const retry=el('button','button outline','Reintentar');retry.onclick=()=>openProfile(p);info.append(retry);}}
async function load(){const status=$('status');status.textContent='Cargando perfiles…';try{const response=await fetch('/api/profiles',{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('No disponible');const data=await response.json();profiles=normalize(data.profiles);const options=$('sort');options.replaceChildren(new Option('Todos los niveles',''));for(const level of [...new Set(profiles.map(p=>p.english))].sort())options.append(new Option(level,level));filters();render();status.textContent=!data.connected?'El catálogo estará disponible próximamente.':!profiles.length?'Todavía no hay perfiles publicados. Volvé a visitarnos pronto.':'';}catch{profiles=[];filters();render();status.replaceChildren(el('span','','No pudimos cargar los perfiles. '));const b=el('button','button outline','Reintentar');b.onclick=load;status.append(b);}}
$('search').oninput=render;$('sort').onchange=render;$('reset').onclick=()=>{$('search').value='';$('sort').value='';country='Todos';filters();render();};$('close').onclick=()=>$('detail').close();$('detail').addEventListener('close',()=>detailRequest?.abort());$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close();}});
if(document.modelContext?.registerTool){const abort=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'filter_profiles',description:'Filtrar los perfiles visibles por nombre, país o inglés.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(typeof input?.query!=='string'||input.query.length>200)throw Error('Búsqueda inválida');$('search').value=input.query;country='Todos';$('sort').value='';filters();render();return results().map(({id,name,country,available})=>({id,name,country,available}));}},{signal:abort.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>abort.abort(),{once:true});}
load();
