import {readCatalog,writeCatalog,clearCatalog} from './catalog-cache.js';
const config=window.STORE_CONFIG;
const $=id=>document.getElementById(id);
let profiles=[],country='Todos',detailRequest,loading=false;
const storage={getItem:key=>sessionStorage.getItem(key),setItem:(key,value)=>sessionStorage.setItem(key,value),removeItem:key=>sessionStorage.removeItem(key)};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function loadingMark(){const wrap=el('span','loading-mark');const logo=el('img');logo.src='/assets/mark.jpg';logo.alt='';wrap.append(logo);return wrap;}
function showLoading(){const status=$('status');const wrap=el('span','catalog-loading');wrap.append(loadingMark(),el('span','','Cargando perfiles…'));status.replaceChildren(wrap);$('products').setAttribute('aria-busy','true');}
function imageFor(p,cls='product-image'){const wrap=el('span',cls);const img=el('img');img.alt='Foto de '+p.name;img.loading='lazy';img.decoding='async';if(p.image){wrap.classList.add('photo-loading');const loader=loadingMark();loader.setAttribute('aria-hidden','true');wrap.append(loader);img.onload=()=>{wrap.classList.remove('photo-loading');loader.remove();};img.src=p.image;}else{wrap.append(el('span','image-fallback','Sin foto'));return wrap;}img.onerror=()=>wrap.replaceChildren(el('span','image-fallback','Foto no disponible'));wrap.append(img);return wrap;}
function safeImage(value){try{const url=new URL(value,location.origin);return url.origin===location.origin&&url.pathname==='/api/profile-photo'?url.href:'';}catch{return '';}}
function normalize(rows){if(!Array.isArray(rows))throw Error('Formato inválido');return rows.filter(p=>p.id&&p.name).map(p=>({id:String(p.id),name:String(p.name),country:String(p.country||'Sin especificar'),english:String(p.english||'Sin especificar'),available:p.available===true,listingPrice:String(p.listingPrice||''),image:safeImage(p.image||'')}));}
function filters(){const root=$('categories');root.replaceChildren(new Option('Todos los países','Todos'));for(const c of [...new Set(profiles.map(p=>p.country))].sort())root.append(new Option(c,c));root.value=country;}
function results(){const term=$('search').value.toLocaleLowerCase('es').trim();const english=$('sort').value;return profiles.filter(p=>(country==='Todos'||p.country===country)&&(!english||p.english===english)&&[p.name,p.country,p.english].join(' ').toLocaleLowerCase('es').includes(term)).sort((a,b)=>a.name.localeCompare(b.name,'es'));}
function nationality(p){const row=el('span','profile-country');const flag=countryFlag(p.country);if(flag){const icon=el('span','country-flag',flag);icon.setAttribute('aria-hidden','true');row.append(icon);}row.append(document.createTextNode(p.country));return row;}
function availability(p){return el('span','availability '+(p.available?'available':'unavailable'),p.available?'Disponible':'No disponible');}
function render(){const rows=results();$('count').textContent=rows.length+' '+(rows.length===1?'perfil':'perfiles');$('products').replaceChildren();$('empty').hidden=rows.length>0||!profiles.length;for(const p of rows){const b=el('button','product');b.type='button';b.setAttribute('aria-label','Ver perfil de '+p.name);b.append(imageFor(p));const heading=el('span','card-heading');heading.append(el('span','product-name',p.name));const flag=countryFlag(p.country);if(flag){const badge=flag==='🇦🇷'?el('img','country-flag'):el('span','country-flag',flag);if(flag==='🇦🇷'){badge.src='/flag-ar.svg';badge.alt=p.country;}badge.setAttribute('aria-label',p.country);badge.title=p.country;heading.append(badge);}if(!flag)heading.append(el('span','card-country',p.country));b.append(heading);const meta=el('span','product-bottom');meta.append(availability(p),el('span','listing-price',p.listingPrice?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(p.listingPrice))+' USD':'—')); b.append(meta);b.onclick=()=>openProfile(p);$('products').append(b);}}
async function openProfile(p){detailRequest?.abort();detailRequest=new AbortController();const root=$('detail-content');const info=el('div','detail-info');const title=el('h2','',p.name);title.id='detail-title';info.append(title,el('p','','Cargando perfil…'));root.replaceChildren(imageFor(p,'detail-picture'),info);if(!$('detail').open)$('detail').showModal();try{const response=await fetch('/api/profile?id='+encodeURIComponent(p.id),{signal:detailRequest.signal,cache:'no-store'});if(!response.ok)throw Error('No disponible');const {profile}=await response.json();root.replaceChildren(profileGallery(profile,p),info);info.replaceChildren(title,nationality(profile),availability(profile),renderProfileSections(profile.details));const link=el('a','button',profile.available?'Consultar por Telegram':'Consultar disponibilidad');const url=new URL('https://t.me/'+config.telegram.replace(/^@/,''));url.searchParams.set('text','Hola, quisiera consultar por el perfil de '+profile.name+' ('+profile.id+').');link.href=url.href;link.target='_blank';link.rel='noopener';info.append(link,el('p','small','Continuá la consulta directamente por Telegram.'));}catch(error){if(error.name==='AbortError')return;info.replaceChildren(title,el('p','','El perfil no está disponible en este momento.'));const retry=el('button','button outline','Reintentar');retry.onclick=()=>openProfile(p);info.append(retry);}}
function applyProfiles(rows){profiles=normalize(rows);const options=$('sort'),selected=options.value;options.replaceChildren(new Option('Inglés: todos',''));for(const level of [...new Set(profiles.map(p=>p.english))].sort())options.append(new Option(level,level));options.value=selected;if(!profiles.some(p=>p.country===country))country='Todos';filters();render();}
async function load(){if(loading)return;loading=true;const status=$('status');if(!profiles.length)showLoading();try{
 const hasCache=(()=>{try{return !!sessionStorage.getItem('dollars.catalog.v2');}catch{return false;}})();if(hasCache){const auth=await fetch('/api/session',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(auth.status===401){clearCatalog(storage);location.replace('/');return;}if(!auth.ok)throw Error('No disponible');const {session}=await auth.json();const saved=readCatalog(storage,session);if(saved){applyProfiles(saved);status.textContent='';}}
 let session='';
 const response=await fetch('/api/profiles',{cache:'no-store',signal:AbortSignal.timeout(30000)});if(response.status===401){clearCatalog(storage);profiles=[];render();location.replace('/');return;}if(!response.ok)throw Error('No disponible');const data=await response.json();applyProfiles(data.profiles);if(data.connected&&data.session)writeCatalog(storage,data.session,profiles);else clearCatalog(storage);status.textContent=!data.connected?'El catálogo estará disponible próximamente.':!profiles.length?'Todavía no hay perfiles publicados. Volvé a visitarnos pronto.':'';
 }catch{clearCatalog(storage);profiles=[];filters();render();status.replaceChildren(el('span','','No pudimos cargar los perfiles. '));const b=el('button','button outline','Reintentar');b.onclick=load;status.append(b);}finally{loading=false;$('products').setAttribute('aria-busy','false');}}
 document.querySelector('.logout').addEventListener('submit',()=>{clearCatalog(storage);profiles=[];$('products').replaceChildren();});
 window.addEventListener('pageshow',e=>{if(e.persisted){profiles=[];$('products').replaceChildren();load();}});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});
 setInterval(()=>{if(!document.hidden)load();},120000);
 if('BroadcastChannel' in window){const updates=new BroadcastChannel('dollars.catalog');updates.onmessage=()=>{clearCatalog(storage);if(!document.hidden)load();};}
$('categories').onchange=()=>{country=$('categories').value;render();};$('about-open').onclick=()=>$('about').showModal();$('about-close').onclick=()=>$('about').close();$('about').addEventListener('click',e=>{if(e.target===$('about')){const r=$('about').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('about').close();}});$('search').oninput=render;$('sort').onchange=render;$('reset').onclick=()=>{$('search').value='';$('sort').value='';country='Todos';filters();render();};$('close').onclick=()=>$('detail').close();$('detail').addEventListener('close',()=>detailRequest?.abort());$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close();}});
if(document.modelContext?.registerTool){const abort=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'filter_profiles',description:'Filtrar los perfiles visibles por nombre, país o inglés.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(typeof input?.query!=='string'||input.query.length>200)throw Error('Búsqueda inválida');$('search').value=input.query;country='Todos';$('sort').value='';filters();render();return results().map(({id,name,country,available})=>({id,name,country,available}));}},{signal:abort.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>abort.abort(),{once:true});}
load();

function profileGallery(profile,fallback){const gallery=el('div','detail-picture gallery');const photos=(profile.images||[]).map(safeImage).filter(Boolean);const picture=imageFor({...fallback,image:photos[0]||fallback.image},'gallery-main');gallery.append(picture);if(photos.length>1){const thumbs=el('div','gallery-thumbs');photos.forEach((image,index)=>{const button=el('button','');button.type='button';button.setAttribute('aria-label',(I18N.lang==='es'?'Ver foto ':'View photo ')+(index+1));button.setAttribute('aria-pressed',String(index===0));button.append(imageFor({...fallback,image},'gallery-thumb'));button.onclick=()=>{gallery.querySelector('.gallery-main').replaceWith(imageFor({...fallback,image},'gallery-main'));thumbs.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));};thumbs.append(button);});gallery.append(thumbs);}return gallery;}
