/* Interface translations only: creator responses remain as submitted. */
(() => {
 const lang=(navigator.languages?.[0]||navigator.language||'es').toLowerCase().startsWith('es')?'es':'en';
 document.documentElement.lang=lang;
 const pairs=[
 ['Perfiles','Profiles'],['Ir al catálogo','Skip to catalog'],['Salir','Sign out'],['EL UNIVERSO DOLL✦ARS','THE DOLL✦ARS UNIVERSE'],['Conocé nuevos perfiles.','Discover new creators.'],['Encontrá el perfil que buscás.','Find the creator you are looking for.'],['Explorar perfiles','Explore profiles'],['Buscar','Search'],['Nombre o país','Name or country'],['Inglés','English'],['Todos los niveles','All levels'],['Todos','All'],['No encontramos perfiles.','No profiles found.'],['Probá con otro nombre, país o nivel de inglés.','Try another name, country or English level.'],['Ver todos','View all'],['Ver perfiles','View profiles'],['Cerrar detalle','Close details'],['Filtrar por país','Filter by country'],['Principal','Main navigation'],['Disponible','Available'],['No disponible','Unavailable'],['Sin foto','No photo'],['Foto no disponible','Photo unavailable'],['Sin especificar','Unspecified'],['No informado','Not provided'],['Cargando perfil…','Loading profile…'],['Cargando perfiles…','Loading profiles…'],['Consultar por Telegram','Contact on Telegram'],['Consultar disponibilidad','Ask about availability'],['Continuá la consulta directamente por Telegram.','Continue your inquiry directly on Telegram.'],['El perfil no está disponible en este momento.','This profile is currently unavailable.'],['Reintentar','Retry'],['El catálogo estará disponible próximamente.','The catalog will be available soon.'],['Todavía no hay perfiles publicados. Volvé a visitarnos pronto.','No profiles have been published yet. Check back soon.'],['No pudimos cargar los perfiles. ','We could not load the profiles. '],
 ['Administración','Administration'],['Bienvenido a DOLL✦ARS','Welcome to DOLL✦ARS'],['Ingresá con tu usuario y contraseña.','Enter your username and password.'],['Ingresá tu contraseña para explorar el catálogo.','Enter your password to explore the catalog.'],['Usuario','Username'],['Contraseña','Password'],['Entrar','Enter'],['Acceso | DOLL✦ARS','Access | DOLL✦ARS'],['DOLL✦ARS | Perfiles','DOLL✦ARS | Profiles'],['Administración | DOLL✦ARS','Administration | DOLL✦ARS'],['Usuario o contraseña incorrectos.','Incorrect username or password.'],['La contraseña no es correcta. Probá nuevamente.','Incorrect password. Please try again.'],['El acceso de administración todavía no está configurado.','Administrator access is not configured yet.'],
 ['PERFORMANCE SNAPSHOT','RESUMEN DE RENDIMIENTO'],['CREATOR PROFILE','PERFIL DEL CREADOR'],['COLLABORATION PREFERENCES','PREFERENCIAS DE COLABORACIÓN'],['Onlyfans Status','Estado de OnlyFans'],['Monthly Revenue','Ingresos mensuales'],['Current Subscribers','Suscriptores actuales'],['Content Library','Biblioteca de contenido'],['Notes / Highlights','Notas / Aspectos destacados'],['Age','Edad'],['Country','País'],['English Level','Nivel de inglés'],['Creator Type','Tipo de creador'],['Smartphone','Smartphone'],['Countries Blocked','Países bloqueados'],['Account access','Acceso a la cuenta'],['Revenue Split (%)','Reparto de ingresos (%)'],['Availability Day/Week','Disponibilidad diaria/semanal'],['Start Availability','Disponibilidad para comenzar'],['Currently Working w/Agency','Actualmente con agencia'],['Social Media Set Up','Redes sociales configuradas'],['Content Type','Tipo de contenido'],
 ['Cerrar sesión','Sign out'],['Gestioná tus perfiles.','Manage your profiles.'],['Revisá las respuestas, aprobá perfiles y actualizá su disponibilidad.','Review responses, approve profiles and update their availability.'],['Actualizar','Refresh'],['Conectá tu hoja de respuestas','Connect your response sheet'],['El panel ya está preparado. Falta instalar el conector actualizado en Google Apps Script.','The panel is ready. Install the updated Google Apps Script connector.'],['Descargar conector actualizado','Download updated connector'],['Buscar perfil','Search profiles'],['Estado de los perfiles','Profile status'],['Pendientes ','Pending '],['Aprobados ','Approved '],['No hay perfiles en esta vista.','No profiles in this view.'],['Las nuevas respuestas aparecerán acá cuando el conector esté activo.','New responses will appear here once the connector is active.'],['Cerrar edición','Close editor'],['REVISIÓN DE PERFIL','PROFILE REVIEW'],[' Aprobado y publicado',' Approved and published'],[' Disponible',' Available'],['Al aprobar un perfil nuevo se marca como disponible automáticamente.','Newly approved profiles are automatically marked as available.'],['Guardar cambios','Save changes'],['Cancelar','Cancel'],['Aprobado','Approved'],['Pendiente','Pending'],['Edad no habilitada','Age not eligible'],['Revisar','Review'],['Aprobar','Approve'],['Cargando respuestas…','Loading responses…'],['Conexión con Google pendiente.','Google connection pending.'],['Guardando cambio…','Saving change…'],['Guardando…','Saving…'],['Perfil habilitado por edad.','Age eligible.'],['No se puede aprobar hasta registrar una edad válida de 18 años o más.','A valid age of 18 or older is required before approval.'],['Describí el tipo de acceso. No ingreses contraseñas ni códigos.','Describe the access type. Do not enter passwords or codes.'],['Incluí la moneda, por ejemplo USD 1.000.','Include the currency, for example USD 1,000.'],['Usá Immediate solo si está confirmado.','Use Immediate only when confirmed.'],['El perfil cambió en la planilla. Cerrá la edición y actualizá antes de guardar.','The profile changed in the sheet. Close the editor and refresh before saving.'],['Solo se pueden aprobar perfiles de mayores de 18 con una edad válida.','Only profiles with a valid age of 18 or older can be approved.'],['Primero hay que conectar la planilla.','Connect the sheet first.'],['Actualizá el conector y ejecutá prepararPerfiles.','Update the connector and run prepararPerfiles.'],['La sesión venció. Volvé a ingresar.','Your session expired. Sign in again.'],['No se pudo acceder a Google. Revisá la conexión e intentá nuevamente.','Google could not be reached. Check the connection and retry.'],['No se pudo completar la operación. Intentá nuevamente.','The operation could not be completed. Please retry.']
 ];
 pairs.push(['Descargá el conector y reemplazá todo el contenido de ','Download the connector and replace all contents of '],[' sin envolverlo en ',' without wrapping it in '],[', sin envolverlo en ', ', without wrapping it in '],['Guardá, seleccioná ','Save, select '],[' y ejecutalo una vez.',' and run it once.'],['Implementá una aplicación web. Configurá su URL y el secreto de conexión en el sitio.','Deploy a web app. Configure its URL and connection secret in the site.']);
 pairs.push(['Contacto por Telegram','Contact on Telegram'],['Nombre','Name'],['Fotos del perfil','Profile photos'],['La primera foto es la portada. Quitar una foto del perfil conserva el archivo original en Drive.','The first photo is the cover. Removing it from the profile preserves the original Drive file.'],['Actualizá el conector de Google para editar el nombre y las fotos. ','Update the Google connector to edit names and photos. '],['Descargar conector','Download connector'],['Sin fotos en el perfil.','No profile photos.'],['Portada','Cover'],['Quitar','Remove'],['Mover antes','Move earlier'],['Mover después','Move later']);
 const dictionary=Object.fromEntries(pairs.filter(([a])=>!['PERFORMANCE SNAPSHOT','CREATOR PROFILE','COLLABORATION PREFERENCES','Onlyfans Status','Monthly Revenue','Current Subscribers','Content Library','Notes / Highlights','Age','Country','English Level','Creator Type','Smartphone','Countries Blocked','Account access','Revenue Split (%)','Availability Day/Week','Start Availability','Currently Working w/Agency','Social Media Set Up','Content Type'].includes(a)));
 const labels=Object.fromEntries(pairs);
 window.I18N={lang,label:value=>lang==='es'?(labels[value]||value):value};
 function translate(value){if(lang==='es')return value;if(dictionary[value])return dictionary[value];return value.replace(/^Respuesta original “Ingreso mensual\/subs”: (.*)\. Completá Monthly Revenue y Current Subscribers por separado; este texto no se muestra en el catálogo\.$/,'Original monthly revenue/subscribers response: $1. Enter revenue and subscribers separately; this reference is not shown in the catalog.').replace(/^(\d+) perfiles recibidos\.$/,'$1 profiles received.').replace(/^(\d+) perfil(es)?$/,'$1 profiles').replace(/^Foto de /,'Photo of ').replace(/^Ver perfil de /,'View profile for ');}
 function visit(root){if(root.nodeType===3){const parent=root.parentElement;if(parent&&!parent.closest('script,style,textarea,.product-name,.profile-country,dd,#edit-title,#detail-title,input')){const next=translate(root.nodeValue);if(next!==root.nodeValue)root.nodeValue=next;}return;}if(root.nodeType!==1)return;for(const attr of ['placeholder','aria-label']){if(root.hasAttribute(attr)){const value=root.getAttribute(attr),next=translate(value);if(value!==next)root.setAttribute(attr,next);}}for(const child of root.childNodes)visit(child);}
 visit(document.documentElement);
 new MutationObserver(changes=>{for(const change of changes){if(change.type==='characterData')visit(change.target);else if(change.type==='attributes')visit(change.target);else for(const node of change.addedNodes)visit(node);}}).observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','aria-label']});
})();
